<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="LibVLCSharp" Version="3.10.1" />
    <PackageVersion Include="LibVLCSharp.WinUI" Version="3.10.1" />
    <PackageVersion Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>
